# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - skadeberegner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9ded931e73274e74a5fca7aa31aa422d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_94d63813f34e47d6b23aa2029e3f6dee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9ded931e73274e74a5fca7aa31aa422d }}/skadeberegner:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'skadeberegner'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_12a838f2d08c43caa29ebf7a50d7e451 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9ded931e73274e74a5fca7aa31aa422d }}/skadeberegner:${{ github.sha }}'